[workspace]
resolver = "2"
members = ["circuits/risc0", "circuits/sp1/program", "circuits/sp1"]

[workspace.dependencies]
risc0-build = "1.0.5"

[profile.dev]
opt-level = 3

[profile.release]
lto = true
