[workspace]
resolver = "2"
members = [
  "circuits/risc0",
  "circuits/sp1/program",
  "circuits/sp1",
  "circuits/plonky2",
]

[workspace.dependencies]
risc0-build = "1.0.5"
bincode = "1.3.3"

[profile.dev]
opt-level = 3

[profile.release]
lto = true
