[package]
name = "nitro_attestation"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = "0.20"
clap = { version = "4.5.28", features = ["derive"] }
byteorder = "1.3"
aws-nitro-enclaves-cose = "0.5.2"
aws-nitro-enclaves-nsm-api = "0.4.0"
